export interface Track {
    id: number;
    title: string;
    artist: string;
    duration: string;
    cover: string;
    youtubeId: string;
    language: 'Hindi' | 'Kannada';
    era?: '1980s' | '1990s' | '2000s' | '2010s' | 'Latest';
    genre?: 'Janapada';
    moods?: Mood[];
    isKaraoke?: boolean;
}

export type Mood = 'Party' | 'Sad' | 'Happy' | 'Driving';

export const eras = ['1980s', '1990s', '2000s', '2010s', 'Latest'] as const;

export const moods: Mood[] = ['Party', 'Sad', 'Happy', 'Driving'];

const baseTracks: Track[] = [
    // ── 1980s Hindi ──
    { id: 1,   title: 'Ek Do Teen',                     artist: 'Tezaab',                         duration: '4:30', cover: '/gallery/promo-serenity.jpg', youtubeId: 'A7x-ZzozsMg', language: 'Hindi',   era: '1980s' },
    { id: 2,   title: 'Papa Kehte Hain',                artist: 'Qayamat Se Qayamat Tak',         duration: '5:02', cover: '/gallery/promo-elegance.jpg', youtubeId: 'E8ytXrzkTNs', language: 'Hindi',   era: '1980s' },
    { id: 3,   title: 'Hawa Hawai',                     artist: 'Mr. India',                      duration: '4:45', cover: '/bottle2.jpeg',               youtubeId: '-8QTG6c6GLk', language: 'Hindi',   era: '1980s' },
    { id: 4,   title: 'Tirchi Topiwale',                artist: 'Tridev',                         duration: '5:15', cover: '/bottle3.jpeg',               youtubeId: 'eYl9i8mH1lI', language: 'Hindi',   era: '1980s' },
    { id: 5,   title: 'Neele Neele Ambar Par',          artist: 'Kalaakaar',                      duration: '5:38', cover: '/bottle4.jpeg',               youtubeId: 'eVnG_Rqfgg4', language: 'Hindi',   era: '1980s' },
    { id: 6,   title: 'Gazab Ka Hai Din',               artist: 'Qayamat Se Qayamat Tak',         duration: '4:55', cover: '/gallery/promo-elegance.jpg', youtubeId: 'DNZAtorsGZM', language: 'Hindi',   era: '1980s' },
    { id: 70,  title: 'Aaj Kal Tere Mere Pyaar Ke Charche', artist: 'Brahmachari',               duration: '4:32', cover: '/bottle3.jpeg',               youtubeId: 'ulEiyaxHx4s', language: 'Hindi',   era: '1980s' },
    { id: 71,  title: 'Dekha Ek Khwab',                 artist: 'Silsila',                        duration: '5:10', cover: '/bottle4.jpeg',               youtubeId: 'qJy5GFoQSPg', language: 'Hindi',   era: '1980s' },
    { id: 72,  title: 'Saiyaara',                       artist: 'Ek Duuje Ke Liye',               duration: '4:48', cover: '/gallery/promo-serenity.jpg', youtubeId: 'ndrOODw8cmg', language: 'Hindi',   era: '1980s' },
    { id: 73,  title: 'Tu Tu Hai Wahi',                 artist: 'Yeh Vaada Raha',                 duration: '4:20', cover: '/gallery/promo-elegance.jpg', youtubeId: 'XFYBij-Vwvo', language: 'Hindi',   era: '1980s' },
    { id: 74,  title: 'Zindagi Pyar Ka Geet Hai',       artist: 'Souten',                         duration: '4:55', cover: '/bottle2.jpeg',               youtubeId: 'Ws82XjyTXE0', language: 'Hindi',   era: '1980s' },
    { id: 75,  title: 'Pal Pal Dil Ke Paas',            artist: 'Blackmail',                      duration: '4:38', cover: '/bottle3.jpeg',               youtubeId: 'Vabo2KVaEwA', language: 'Hindi',   era: '1980s' },

    // ── 1980s Kannada ──
    { id: 7,   title: 'Jotheyali Jothe Jotheyali',      artist: 'Geetha',                         duration: '4:20', cover: '/bottle2.jpeg',               youtubeId: '5ABB10YBeSE', language: 'Kannada', era: '1980s' },
    { id: 8,   title: 'Baalu Belakayithu',              artist: 'Haalu Jenu',                     duration: '4:35', cover: '/bottle3.jpeg',               youtubeId: 'NQBDlUbHCNs', language: 'Kannada', era: '1980s' },
    { id: 9,   title: 'Ganga Yamuna Sangama',           artist: 'Anuraga Aralithu',               duration: '3:58', cover: '/bottle4.jpeg',               youtubeId: 'GLJ4pjJldp0', language: 'Kannada', era: '1980s' },
    { id: 10,  title: 'Kelade Nimageega',               artist: 'Geetha',                         duration: '4:42', cover: '/gallery/promo-serenity.jpg', youtubeId: 'Hbu5vMjqXLs', language: 'Kannada', era: '1980s' },
    { id: 11,  title: 'Nammoora Mandara Hoove',         artist: 'Aalemane',                       duration: '5:10', cover: '/gallery/promo-elegance.jpg', youtubeId: 'tEAvA9SNJ4Y', language: 'Kannada', era: '1980s' },
    { id: 12,  title: 'Olume Siriya',                   artist: 'Bangarada Jinke',                duration: '4:48', cover: '/bottle2.jpeg',               youtubeId: 'ckTZmTvXm8o', language: 'Kannada', era: '1980s' },
    { id: 13,  title: 'Anupama Cheluvu',                artist: 'Anupama',                        duration: '4:15', cover: '/bottle3.jpeg',               youtubeId: 'JER4prFqxSg', language: 'Kannada', era: '1980s' },
    { id: 14,  title: 'Haayaada Ee Sanje',              artist: 'Vasantha Geetha',                duration: '5:10', cover: '/gallery/promo-elegance.jpg', youtubeId: 'cMwrjbUhK5s', language: 'Kannada', era: '1980s' },
    { id: 15,  title: 'Huttidare Kannada',              artist: 'Akasmika',                       duration: '4:48', cover: '/bottle2.jpeg',               youtubeId: 'jNoaf88ecok', language: 'Kannada', era: '1980s' },
    { id: 100, title: 'Baanigondu Elle Ellide',         artist: 'Premada Kanike',                 duration: '4:25', cover: '/bottle4.jpeg',               youtubeId: 'eDNu8x8su48', language: 'Kannada', era: '1980s' },
    { id: 101, title: 'Endendu Ninnanu Marethu',        artist: 'Eradu Kanasu',                   duration: '4:42', cover: '/gallery/promo-serenity.jpg', youtubeId: '-knlhwCL9zY', language: 'Kannada', era: '1980s' },
    { id: 102, title: 'Hoovu Cheluvella',               artist: 'Kalpana',                        duration: '4:15', cover: '/gallery/promo-elegance.jpg', youtubeId: 'zCFGMTSVf8I', language: 'Kannada', era: '1980s' },
    { id: 103, title: 'Hrudaya Rangoli',                artist: 'Pallavi Anupallavi',             duration: '4:50', cover: '/bottle3.jpeg',               youtubeId: 'qy6Sa3S9lMo', language: 'Kannada', era: '1980s' },
    { id: 104, title: 'Kanasalu Neene Manasalu Neene',  artist: 'Bayalu Dari',                    duration: '4:30', cover: '/bottle4.jpeg',               youtubeId: '8j_KyfTRA1A', language: 'Kannada', era: '1980s' },
    { id: 105, title: 'Kannalli Yeno Minchondu',        artist: 'Vasantha Geetha',                duration: '4:18', cover: '/gallery/promo-serenity.jpg', youtubeId: 'hqKDzfVwrGY', language: 'Kannada', era: '1980s' },
    { id: 106, title: 'Kasturi Nivasa',                 artist: 'Kasturi Nivasa',                 duration: '4:55', cover: '/gallery/promo-elegance.jpg', youtubeId: 'nDf1nX9xJ1Y', language: 'Kannada', era: '1980s' },
    { id: 107, title: 'Nagu Endide',                    artist: 'Pallavi Anupallavi',             duration: '4:10', cover: '/bottle2.jpeg',               youtubeId: '5RuMpVFPMHQ', language: 'Kannada', era: '1980s' },
    { id: 108, title: 'Naguva Nayana',                  artist: 'Pallavi Anupallavi',             duration: '4:38', cover: '/bottle3.jpeg',               youtubeId: '7nv55Kl5ldA', language: 'Kannada', era: '1980s' },
    { id: 109, title: 'O Priyathama',                   artist: 'Kaviratna Kalidasa',             duration: '4:45', cover: '/bottle4.jpeg',               youtubeId: 'TbMq3T5ji2w', language: 'Kannada', era: '1980s' },
    { id: 110, title: 'Premadalli Snehadalli',          artist: 'Ranganayaki',                    duration: '4:22', cover: '/gallery/promo-serenity.jpg', youtubeId: 'SMkoYwFeP_0', language: 'Kannada', era: '1980s' },

    // ── 1990s Hindi ──
    { id: 16,  title: 'Chaiyya Chaiyya',                artist: 'Dil Se',                         duration: '6:23', cover: '/bottle4.jpeg',               youtubeId: 'i9A9NuTHUag', language: 'Hindi',   era: '1990s' },
    { id: 17,  title: 'Pehla Nasha',                    artist: 'Jo Jeeta Wohi Sikandar',         duration: '5:12', cover: '/gallery/promo-serenity.jpg', youtubeId: 'Ki41AKu0iHc', language: 'Hindi',   era: '1990s' },
    { id: 18,  title: 'Tujhe Dekha To',                 artist: 'DDLJ',                           duration: '5:45', cover: '/gallery/promo-elegance.jpg', youtubeId: 'A-TsKDZPnJs', language: 'Hindi',   era: '1990s' },
    { id: 19,  title: 'Chunnari Chunnari',              artist: 'Biwi No. 1',                     duration: '5:30', cover: '/bottle2.jpeg',               youtubeId: 'dRLwMAGMJnQ', language: 'Hindi',   era: '1990s' },
    { id: 20,  title: 'O O Jaane Jaana',                artist: 'Pyar Kiya Toh Darna Kya',        duration: '5:08', cover: '/bottle3.jpeg',               youtubeId: '9SE6B0h-4-Q', language: 'Hindi',   era: '1990s' },
    { id: 21,  title: 'Didi Tera Devar Deewana',        artist: 'Hum Aapke Hain Koun',            duration: '4:55', cover: '/bottle4.jpeg',               youtubeId: 'hTnJzM7BSR0', language: 'Hindi',   era: '1990s' },
    { id: 22,  title: 'Jumma Chumma De De',             artist: 'Hum',                            duration: '6:10', cover: '/gallery/promo-serenity.jpg', youtubeId: 'ijGumwamEQU', language: 'Hindi',   era: '1990s' },
    { id: 76,  title: 'Aye Ajnabi',                     artist: 'Dil Se',                         duration: '4:55', cover: '/gallery/promo-elegance.jpg', youtubeId: 'TdUu05Svkl8', language: 'Hindi',   era: '1990s' },
    { id: 77,  title: 'Dil To Pagal Hai',               artist: 'Dil To Pagal Hai',               duration: '5:18', cover: '/bottle2.jpeg',               youtubeId: 'QPXRP61ZgxA', language: 'Hindi',   era: '1990s' },
    { id: 78,  title: 'Main Duniya Bhula Doonga',       artist: 'Aashiqui',                       duration: '5:02', cover: '/bottle3.jpeg',               youtubeId: 'otQmzlm-s7Q', language: 'Hindi',   era: '1990s' },
    { id: 79,  title: 'Mera Dil Bhi Kitna Pagal Hai',   artist: 'Saajan',                         duration: '4:45', cover: '/bottle4.jpeg',               youtubeId: 'FsNc7I33w60', language: 'Hindi',   era: '1990s' },
    { id: 80,  title: 'Tip Tip Barsa Paani',            artist: 'Mohra',                          duration: '4:28', cover: '/gallery/promo-serenity.jpg', youtubeId: 'BtlnpBb4O8E', language: 'Hindi',   era: '1990s' },
    { id: 81,  title: 'Tu Cheez Badi Hai Mast Mast',    artist: 'Mohra',                          duration: '4:35', cover: '/gallery/promo-elegance.jpg', youtubeId: 'ZrQS-ZtDy-o', language: 'Hindi',   era: '1990s' },

    // ── 1990s Kannada ──
    { id: 23,  title: 'Janumada Jodi',                  artist: 'Janumada Jodi',                  duration: '4:22', cover: '/bottle3.jpeg',               youtubeId: 'XDj4HYCCh3g', language: 'Kannada', era: '1990s' },
    { id: 24,  title: 'Nooru Janmaku',                  artist: 'America America',                duration: '4:05', cover: '/bottle4.jpeg',               youtubeId: 'm5mdnknNDyw', language: 'Kannada', era: '1990s' },
    { id: 25,  title: 'Ninna Nodalentho',               artist: 'Mussanje Maathu',                duration: '4:38', cover: '/gallery/promo-serenity.jpg', youtubeId: 'gTUqkF616yI', language: 'Kannada', era: '1990s' },
    { id: 26,  title: 'Nalivaa Gulaabi Hoove',          artist: 'Auto Raja',                      duration: '3:55', cover: '/gallery/promo-elegance.jpg', youtubeId: 'd8pMgz-w9x8', language: 'Kannada', era: '1990s' },
    { id: 27,  title: 'Prema Chandrama',                artist: 'Yajamana',                       duration: '4:30', cover: '/bottle2.jpeg',               youtubeId: '4Mgw_Qn2064', language: 'Kannada', era: '1990s' },
    { id: 111, title: 'Ee Bhoomi Bannada Buguri',       artist: 'Mahakshatriya',                  duration: '4:35', cover: '/bottle3.jpeg',               youtubeId: 'MmwuWX_Fv3E', language: 'Kannada', era: '1990s' },
    { id: 112, title: 'Manase Baduku',                  artist: 'Amruthavarshini',                duration: '4:18', cover: '/bottle4.jpeg',               youtubeId: 'ocFVVzcMIfc', language: 'Kannada', era: '1990s' },
    { id: 113, title: 'O Mallige Ninnondige',           artist: 'Anuraga Sangama',                duration: '4:42', cover: '/gallery/promo-serenity.jpg', youtubeId: 'gnaXl1zJr0c', language: 'Kannada', era: '1990s' },
    { id: 114, title: 'Yaarige Beku',                   artist: 'Sipayi',                         duration: '4:50', cover: '/gallery/promo-elegance.jpg', youtubeId: 'LpLn6K7IBvg', language: 'Kannada', era: '1990s' },
    { id: 115, title: 'Yaava Mohana Murali',            artist: 'America America',                duration: '4:22', cover: '/bottle2.jpeg',               youtubeId: 'g3Nbx1u_70o', language: 'Kannada', era: '1990s' },

    // ── 2000s Hindi ──
    { id: 28,  title: 'Bole Chudiyan',                  artist: 'Kabhi Khushi Kabhie Gham',       duration: '5:18', cover: '/gallery/promo-serenity.jpg', youtubeId: 'cfi2Trletjw', language: 'Hindi',   era: '2000s' },
    { id: 29,  title: 'Kal Ho Naa Ho',                  artist: 'Kal Ho Naa Ho',                  duration: '5:19', cover: '/bottle3.jpeg',               youtubeId: 'fyJvsb2cQy8', language: 'Hindi',   era: '2000s' },
    { id: 30,  title: 'Kajra Re',                       artist: 'Bunty Aur Babli',                duration: '5:42', cover: '/bottle4.jpeg',               youtubeId: 'nmy5A7fo0g4', language: 'Hindi',   era: '2000s' },
    { id: 31,  title: 'Tum Ko Dekha To',                artist: 'Jagjit Singh',                   duration: '5:55', cover: '/gallery/promo-serenity.jpg', youtubeId: 'WtPbNKk9XpU', language: 'Hindi',   era: '2000s' },
    { id: 32,  title: 'Mauja Hi Mauja',                 artist: 'Jab We Met',                     duration: '5:28', cover: '/gallery/promo-elegance.jpg', youtubeId: 'aPHsp9X2mBE', language: 'Hindi',   era: '2000s' },
    { id: 33,  title: 'Desi Girl',                      artist: 'Dostana',                        duration: '4:15', cover: '/bottle2.jpeg',               youtubeId: '28Zsch1QjPI', language: 'Hindi',   era: '2000s' },
    { id: 34,  title: 'Pehli Nazar Mein',               artist: 'Race',                           duration: '5:05', cover: '/bottle3.jpeg',               youtubeId: 'lQD5iaGmzX0', language: 'Hindi',   era: '2000s' },
    { id: 35,  title: 'Teri Ore',                       artist: 'Singh Is Kinng',                 duration: '5:32', cover: '/bottle4.jpeg',               youtubeId: '5ldRVSQ3JmE', language: 'Hindi',   era: '2000s' },
    { id: 82,  title: 'Agar Tum Mil Jao',               artist: 'Zeher',                          duration: '4:28', cover: '/gallery/promo-serenity.jpg', youtubeId: 'olTVf-fKfKw', language: 'Hindi',   era: '2000s' },
    { id: 83,  title: 'Dus Bahane',                     artist: 'Dus',                            duration: '4:45', cover: '/gallery/promo-elegance.jpg', youtubeId: 'mIWpsOjQNDw', language: 'Hindi',   era: '2000s' },
    { id: 84,  title: 'Jadu Hai Nasha Hai',             artist: 'Jism',                           duration: '5:05', cover: '/bottle2.jpeg',               youtubeId: 'T_MPeEX-aIs', language: 'Hindi',   era: '2000s' },
    { id: 85,  title: 'Mitwa',                          artist: 'Kabhi Alvida Naa Kehna',         duration: '5:22', cover: '/bottle3.jpeg',               youtubeId: 'XllMnMHdiLE', language: 'Hindi',   era: '2000s' },
    { id: 86,  title: 'Suraj Hua Maddham',              artist: 'Kabhi Khushi Kabhie Gham',       duration: '5:38', cover: '/bottle4.jpeg',               youtubeId: '4LqqQfMweuk', language: 'Hindi',   era: '2000s' },
    { id: 87,  title: 'Tere Naam',                      artist: 'Tere Naam',                      duration: '4:52', cover: '/gallery/promo-serenity.jpg', youtubeId: 'kN0_SKPjFVA', language: 'Hindi',   era: '2000s' },
    { id: 88,  title: 'Tum Se Hi',                      artist: 'Jab We Met',                     duration: '4:35', cover: '/gallery/promo-elegance.jpg', youtubeId: 'xo3ex0xDYVA', language: 'Hindi',   era: '2000s' },

    // ── 2000s Kannada ──
    { id: 36,  title: 'Yaare Nee Devatheya',            artist: 'Ambari',                         duration: '4:35', cover: '/gallery/promo-serenity.jpg', youtubeId: 'bF6wcqMxmOM', language: 'Kannada', era: '2000s' },
    { id: 37,  title: 'Minchagi Neenu Baralu',          artist: 'Gaalipata',                      duration: '4:12', cover: '/gallery/promo-elegance.jpg', youtubeId: 'cTYyAEvsOZs', language: 'Kannada', era: '2000s' },
    { id: 38,  title: 'Anisuthide',                     artist: 'Mungaru Male',                   duration: '4:48', cover: '/bottle2.jpeg',               youtubeId: 'V6XLCmxDoCE', language: 'Kannada', era: '2000s' },
    { id: 39,  title: 'Mungaru Maleye',                 artist: 'Mungaru Male',                   duration: '3:58', cover: '/bottle3.jpeg',               youtubeId: 'b04OqmvxFB8', language: 'Kannada', era: '2000s' },
    { id: 40,  title: 'Onde Ondu Saari',                artist: 'Mungaru Male',                   duration: '4:22', cover: '/bottle4.jpeg',               youtubeId: 'yshEznPQS54', language: 'Kannada', era: '2000s' },
    { id: 41,  title: 'Open Hairu Bitkondu',            artist: 'Adhyaksha',                      duration: '4:10', cover: '/gallery/promo-serenity.jpg', youtubeId: 'Elas5AL4nto', language: 'Kannada', era: '2000s' },
    { id: 42,  title: 'Paravashanadenu',                artist: 'Paramathma',                     duration: '4:28', cover: '/gallery/promo-elegance.jpg', youtubeId: 'n9oi-wlQD9Y', language: 'Kannada', era: '2000s' },
    { id: 116, title: 'Araluthiru',                     artist: 'Mungaru Male',                   duration: '4:15', cover: '/bottle2.jpeg',               youtubeId: 'CPR36NsEn2Q', language: 'Kannada', era: '2000s' },
    { id: 117, title: 'Banna Banna Elu Banna',          artist: 'Ee Bandhana',                    duration: '4:30', cover: '/bottle3.jpeg',               youtubeId: 'O8nsJOG7J9A', language: 'Kannada', era: '2000s' },
    { id: 118, title: 'Car Car Car',                    artist: 'Nanna Preethiya Hudugi',         duration: '3:58', cover: '/bottle4.jpeg',               youtubeId: 'lKxbApBiT_g', language: 'Kannada', era: '2000s' },
    { id: 119, title: 'Jothe Jotheyali',                artist: 'Vamshi',                         duration: '4:40', cover: '/gallery/promo-serenity.jpg', youtubeId: 'Mj8WDgtI_XE', language: 'Kannada', era: '2000s' },
    { id: 120, title: 'Kariya I Love You',              artist: 'Kariya',                         duration: '4:12', cover: '/gallery/promo-elegance.jpg', youtubeId: 'o4s5rDgmUo4', language: 'Kannada', era: '2000s' },
    { id: 121, title: 'Male Ninthu Hoda Mele',          artist: 'Milana',                         duration: '4:48', cover: '/bottle2.jpeg',               youtubeId: '3AwG5aM64uA', language: 'Kannada', era: '2000s' },
    { id: 122, title: 'Marali Mareyagi',                artist: 'Savari',                         duration: '4:22', cover: '/bottle3.jpeg',               youtubeId: 'uTOwN3UQzXs', language: 'Kannada', era: '2000s' },
    { id: 123, title: 'Innoo Anisutide',                artist: 'Neene Bari Neene',               duration: '4:35', cover: '/bottle4.jpeg',               youtubeId: 'dUwCF73n8rc', language: 'Kannada', era: '2000s' },
    { id: 124, title: 'Yenagali',                       artist: 'Mussanje Maathu',                duration: '4:18', cover: '/gallery/promo-serenity.jpg', youtubeId: 'ZFxTICyR1EE', language: 'Kannada', era: '2000s' },

    // ── 2010s Hindi ──
    { id: 43,  title: 'Tum Hi Ho',                      artist: 'Aashiqui 2',                     duration: '4:22', cover: '/bottle2.jpeg',               youtubeId: 'Umqb9KENgmk', language: 'Hindi',   era: '2010s' },
    { id: 44,  title: 'Kabira',                         artist: 'Yeh Jawaani Hai Deewani',        duration: '4:50', cover: '/bottle3.jpeg',               youtubeId: '7jZwAl0ArQw', language: 'Hindi',   era: '2010s' },
    { id: 45,  title: 'Zaalima',                        artist: 'Raees',                          duration: '4:32', cover: '/bottle4.jpeg',               youtubeId: 'YJZYLQhGQLg', language: 'Hindi',   era: '2010s' },
    { id: 46,  title: 'Nashe Si Chadh Gayi',            artist: 'Befikre',                        duration: '3:55', cover: '/gallery/promo-serenity.jpg', youtubeId: '_tEjIYtGBwc', language: 'Hindi',   era: '2010s' },
    { id: 47,  title: 'Dil Diyan Gallan',               artist: 'Tiger Zinda Hai',                duration: '4:48', cover: '/gallery/promo-elegance.jpg', youtubeId: 'POvFEQaK634', language: 'Hindi',   era: '2010s' },
    { id: 48,  title: 'Humsafar',                       artist: 'Badrinath Ki Dulhania',          duration: '5:12', cover: '/bottle2.jpeg',               youtubeId: 'tYgy4fF9iJA', language: 'Hindi',   era: '2010s' },
    { id: 49,  title: 'Swag Se Swagat',                 artist: 'Tiger Zinda Hai',                duration: '3:28', cover: '/bottle3.jpeg',               youtubeId: 'm7xDE8MMKcQ', language: 'Hindi',   era: '2010s' },
    { id: 50,  title: 'Gali Gali',                      artist: 'KGF',                            duration: '3:32', cover: '/bottle2.jpeg',               youtubeId: 'e9QFfGATfB8', language: 'Hindi',   era: '2010s' },
    { id: 89,  title: 'Agar Tum Saath Ho',              artist: 'Tamasha',                        duration: '5:30', cover: '/bottle3.jpeg',               youtubeId: 'dhY8jRNELUc', language: 'Hindi',   era: '2010s' },
    { id: 90,  title: 'Channa Mereya',                  artist: 'Ae Dil Hai Mushkil',             duration: '4:50', cover: '/bottle4.jpeg',               youtubeId: 'bzSTpdcs-EI', language: 'Hindi',   era: '2010s' },
    { id: 91,  title: 'Galliyan',                       artist: 'Ek Villain',                     duration: '4:22', cover: '/gallery/promo-serenity.jpg', youtubeId: 'PL8X5gq9ZlQ', language: 'Hindi',   era: '2010s' },
    { id: 92,  title: 'Raabta',                         artist: 'Agent Vinod',                    duration: '4:15', cover: '/gallery/promo-elegance.jpg', youtubeId: 'nzDcwJCn6cs', language: 'Hindi',   era: '2010s' },

    // ── 2010s Kannada ──
    { id: 51,  title: 'Belageddu',                      artist: 'Kirik Party',                    duration: '4:12', cover: '/bottle4.jpeg',               youtubeId: 'g5JfqN4L26Q', language: 'Kannada', era: '2010s' },
    { id: 52,  title: 'Chuttu Chuttu',                  artist: 'Raambo 2',                       duration: '3:45', cover: '/gallery/promo-serenity.jpg', youtubeId: 'WMGEr6Yd3T8', language: 'Kannada', era: '2010s' },
    { id: 53,  title: 'Bombe Helutaithe',               artist: 'Raajakumara',                    duration: '4:30', cover: '/gallery/promo-elegance.jpg', youtubeId: 'oWEfDKxq_hE', language: 'Kannada', era: '2010s' },
    { id: 54,  title: 'Mungaru Maleyalli',              artist: 'Andondittu Kaala',               duration: '3:58', cover: '/bottle2.jpeg',               youtubeId: 'PMzTLWTWLZU', language: 'Kannada', era: '2010s' },
    { id: 55,  title: 'Geleya Ennale',                  artist: 'Mass Leader',                    duration: '4:15', cover: '/bottle3.jpeg',               youtubeId: 'HvWLRLFCXFs', language: 'Kannada', era: '2010s' },
    { id: 56,  title: 'Sanju Mathu Geetha',             artist: 'Sanju Weds Geetha',              duration: '4:42', cover: '/bottle4.jpeg',               youtubeId: 'w1T17HmS22A', language: 'Kannada', era: '2010s' },
    { id: 57,  title: 'Naane Neenanthe',                artist: 'BRAT',                           duration: '5:10', cover: '/gallery/promo-serenity.jpg', youtubeId: 'uiI8z-vOmPE', language: 'Kannada', era: '2010s' },
    { id: 58,  title: 'Salaam Rocky Bhai',              artist: 'KGF Chapter 1',                  duration: '3:48', cover: '/bottle3.jpeg',               youtubeId: '6Hvc-xpNTME', language: 'Kannada', era: '2010s' },
    { id: 59,  title: 'Dheera Dheera',                  artist: 'KGF',                            duration: '4:22', cover: '/bottle4.jpeg',               youtubeId: 'V3w3N4UMbdk', language: 'Kannada', era: '2010s' },
    { id: 125, title: 'Karagida Baaninalli',            artist: 'Simple Agi Ondh Love Story',     duration: '4:28', cover: '/gallery/promo-serenity.jpg', youtubeId: 'OjJxz88iKKY', language: 'Kannada', era: '2010s' },
    { id: 126, title: 'Ninna Snehadinda',               artist: 'Mugulu Nage',                    duration: '4:15', cover: '/gallery/promo-elegance.jpg', youtubeId: 'cM3LF6fNnk0', language: 'Kannada', era: '2010s' },
    { id: 127, title: 'Annthamma',                      artist: 'Mr & Mrs Ramachari',             duration: '4:05', cover: '/bottle2.jpeg',               youtubeId: 'dCxZrNtgFxc', language: 'Kannada', era: '2010s' },
    { id: 128, title: 'Usire Usire',                    artist: 'Hebbuli',                        duration: '4:38', cover: '/bottle3.jpeg',               youtubeId: 'M0o8VGY0MCA', language: 'Kannada', era: '2010s' },

    // ── Latest (2020s) Hindi ──
    { id: 60,  title: 'Akhiyaan Gulaab',                artist: 'Teri Baaton Mein Aisa Uljha Jiya', duration: '4:28', cover: '/gallery/promo-elegance.jpg', youtubeId: '0XJVTg3gMCw', language: 'Hindi',   era: 'Latest' },
    { id: 61,  title: 'Satyanaas',                      artist: 'Chandu Champion',                duration: '3:55', cover: '/bottle2.jpeg',               youtubeId: 'yVpHofE4jD0', language: 'Hindi',   era: 'Latest' },
    { id: 62,  title: 'Tauba Tauba',                    artist: 'Bad Newz',                       duration: '3:42', cover: '/bottle3.jpeg',               youtubeId: 'c5AbMnDz8p4', language: 'Hindi',   era: 'Latest' },
    { id: 63,  title: 'Vaada Hai',                      artist: "O'Romeo",                        duration: '4:15', cover: '/bottle4.jpeg',               youtubeId: 'FLbbf4-eeI4', language: 'Hindi',   era: 'Latest' },
    { id: 64,  title: 'Zinda Banda',                    artist: 'Jawan',                          duration: '3:18', cover: '/gallery/promo-serenity.jpg', youtubeId: 'CaJ22UtBj18', language: 'Hindi',   era: 'Latest' },
    { id: 65,  title: 'Main Hoon',                      artist: 'Battle Of Galwan',               duration: '4:05', cover: '/gallery/promo-elegance.jpg', youtubeId: 'SakKiuHy5Q4', language: 'Hindi',   era: 'Latest' },
    { id: 93,  title: 'Chaleya',                        artist: 'Jawan',                          duration: '3:45', cover: '/bottle2.jpeg',               youtubeId: 'c_zhNAqogiA', language: 'Hindi',   era: 'Latest' },
    { id: 94,  title: 'Gehra Hua',                      artist: 'Dhurandhar',                     duration: '4:12', cover: '/bottle3.jpeg',               youtubeId: 'kBvkTSV_SQE', language: 'Hindi',   era: 'Latest' },
    { id: 95,  title: 'Heeriye',                        artist: 'Jasleen Royal ft. Arijit Singh', duration: '4:28', cover: '/bottle4.jpeg',               youtubeId: '6_Uq8YnH2ME', language: 'Hindi',   era: 'Latest' },
    { id: 96,  title: 'Kesariya',                       artist: 'Brahmastra',                     duration: '4:28', cover: '/gallery/promo-serenity.jpg', youtubeId: 'BddP6PYo2gs', language: 'Hindi',   era: 'Latest' },
    { id: 97,  title: 'Lutt Le Gaya',                   artist: 'Dhurandhar',                     duration: '3:55', cover: '/gallery/promo-elegance.jpg', youtubeId: '5lGFBWflE04', language: 'Hindi',   era: 'Latest' },
    { id: 98,  title: 'Param Sundari',                  artist: 'Mimi',                           duration: '4:08', cover: '/bottle2.jpeg',               youtubeId: 'oBFf6PBHhCY', language: 'Hindi',   era: 'Latest' },
    { id: 99,  title: 'Tere Pyaar Mein',                artist: 'Tu Jhoothi Main Makkaar',        duration: '4:42', cover: '/bottle3.jpeg',               youtubeId: 'E9a3JHHF0Yw', language: 'Hindi',   era: 'Latest' },

    // ── Latest (2020s) Kannada ──
    { id: 66,  title: 'Idre Nemdiyaag Irbek',           artist: 'The Devil',                      duration: '4:55', cover: '/gallery/promo-serenity.jpg', youtubeId: 'eOVP6Qaz3xg', language: 'Kannada', era: 'Latest' },
    { id: 67,  title: 'Bangle Bangari',                 artist: 'EKKA',                           duration: '5:08', cover: '/gallery/promo-elegance.jpg', youtubeId: 'Zyf7DXm7HJI', language: 'Kannada', era: 'Latest' },
    { id: 68,  title: 'Ayyo Sivane',                    artist: 'Cult',                           duration: '4:15', cover: '/bottle2.jpeg',               youtubeId: 'mHOuQpBULIA', language: 'Kannada', era: 'Latest' },
    { id: 69,  title: 'Shiva Shiva',                    artist: 'KD',                             duration: '3:42', cover: '/bottle3.jpeg',               youtubeId: '5J5v8zB4kP4', language: 'Kannada', era: 'Latest' },
    { id: 129, title: 'Nee Sigoovaregu',                artist: 'Bhajarangi 2',                   duration: '4:22', cover: '/bottle4.jpeg',               youtubeId: 'i9E_MjNlm_A', language: 'Kannada', era: 'Latest' },
    { id: 130, title: 'Brahmakalasha',                  artist: 'Kantara',                        duration: '3:58', cover: '/gallery/promo-serenity.jpg', youtubeId: '3sD3FDZzQIo', language: 'Kannada', era: 'Latest' },
    { id: 131, title: 'Dhamaka',                        artist: 'Siddu Moolimani',                duration: '4:10', cover: '/gallery/promo-elegance.jpg', youtubeId: 'Yq2sJpSS4DM', language: 'Kannada', era: 'Latest' },
    { id: 132, title: 'Naavaduva Nudiye',               artist: 'Gandhada Gudi 2',                duration: '4:35', cover: '/bottle2.jpeg',               youtubeId: 'V-G3MYN5Gm0', language: 'Kannada', era: 'Latest' },
    { id: 133, title: 'Sapta Sagaradaache Ello',        artist: 'Sapta Sagaradaache Ello',        duration: '4:48', cover: '/bottle3.jpeg',               youtubeId: 'z9bRCXWG2LA', language: 'Kannada', era: 'Latest' },
    { id: 134, title: 'Singara Siriye',                 artist: 'Kantara',                        duration: '4:05', cover: '/bottle4.jpeg',               youtubeId: 'dAVTPTYdaVQ', language: 'Kannada', era: 'Latest' },
    { id: 135, title: 'Sojugada Soojumallige',          artist: 'GGVV',                           duration: '4:18', cover: '/gallery/promo-serenity.jpg', youtubeId: '4LFWC85XQZM', language: 'Kannada', era: 'Latest' },
    { id: 136, title: 'Sulthana',                       artist: 'KGF Chapter 2',                  duration: '3:52', cover: '/gallery/promo-elegance.jpg', youtubeId: '1HMCS6KPBIM', language: 'Kannada', era: 'Latest' },
    { id: 137, title: 'Thoogire Rangana',               artist: 'Dr. Vidyabhushana',              duration: '4:25', cover: '/bottle2.jpeg',               youtubeId: 'p1UBQNVRsGM', language: 'Kannada', era: 'Latest' },
    { id: 138, title: 'Toofan',                         artist: 'KGF Chapter 2',                  duration: '4:12', cover: '/bottle3.jpeg',               youtubeId: '7q4h2RFBF5E', language: 'Kannada', era: 'Latest' },
    { id: 139, title: 'Varaha Roopam',                  artist: 'Kantara',                        duration: '4:42', cover: '/bottle4.jpeg',               youtubeId: 'xt7i1LTQvPs', language: 'Kannada', era: 'Latest' },

    // ── Karaoke: Hindi (1980s-1990s) ──
    { id: 200, title: 'Ek Do Teen (Karaoke)',                     artist: 'Tezaab',                         duration: '4:30', cover: '/gallery/promo-serenity.jpg', youtubeId: 'bN1W6h2zimE', language: 'Hindi',   era: '1980s' },
    { id: 201, title: 'Papa Kehte Hain (Karaoke)',                artist: 'Qayamat Se Qayamat Tak',         duration: '5:02', cover: '/gallery/promo-elegance.jpg', youtubeId: '6K5z_B-ESeI', language: 'Hindi',   era: '1980s' },
    { id: 202, title: 'Hawa Hawai (Karaoke)',                     artist: 'Mr. India',                      duration: '4:45', cover: '/bottle2.jpeg',               youtubeId: 'xZKKRAIrJv8', language: 'Hindi',   era: '1980s' },
    { id: 203, title: 'Neele Neele Ambar Par (Karaoke)',          artist: 'Kalaakaar',                      duration: '5:38', cover: '/bottle4.jpeg',               youtubeId: 'lOx4uyttIw', language: 'Hindi',   era: '1980s' },
    { id: 204, title: 'Gazab Ka Hai Din (Karaoke)',               artist: 'Qayamat Se Qayamat Tak',         duration: '4:55', cover: '/gallery/promo-serenity.jpg', youtubeId: 'iiACaCpwbv0', language: 'Hindi',   era: '1980s' },
    { id: 205, title: 'Chaiyya Chaiyya (Karaoke)',                artist: 'Dil Se',                         duration: '6:23', cover: '/bottle4.jpeg',               youtubeId: 'UnLm6MqtvyI', language: 'Hindi',   era: '1990s' },
    { id: 206, title: 'Pehla Nasha (Karaoke)',                    artist: 'Jo Jeeta Wohi Sikandar',         duration: '5:12', cover: '/gallery/promo-serenity.jpg', youtubeId: '41C_asLw0gQ', language: 'Hindi',   era: '1990s' },
    { id: 207, title: 'Tujhe Dekha To (Karaoke)',                 artist: 'DDLJ',                           duration: '5:45', cover: '/gallery/promo-elegance.jpg', youtubeId: 'EApzbYjCOig', language: 'Hindi',   era: '1990s' },
    { id: 208, title: 'Didi Tera Devar Deewana (Karaoke)',        artist: 'Hum Aapke Hain Koun',            duration: '4:55', cover: '/bottle4.jpeg',               youtubeId: 'CS3B473fzsc', language: 'Hindi',   era: '1990s' },
    { id: 209, title: 'Jumma Chumma De De (Karaoke)',             artist: 'Hum',                            duration: '6:10', cover: '/gallery/promo-serenity.jpg', youtubeId: 'ZQ_AxsLFpDQ', language: 'Hindi',   era: '1990s' },

    // ── Karaoke: Kannada (1980s-1990s) ──
    { id: 210, title: 'Jotheyali Jothe Jotheyali (Karaoke)',      artist: 'Geetha',                         duration: '4:20', cover: '/bottle2.jpeg',               youtubeId: 'UAP-thiK8ZE', language: 'Kannada', era: '1980s' },
    { id: 211, title: 'Baalu Belakayithu (Karaoke)',              artist: 'Haalu Jenu',                     duration: '4:35', cover: '/bottle3.jpeg',               youtubeId: 'ZyWk5GhwoVg', language: 'Kannada', era: '1980s' },
    { id: 212, title: 'Ganga Yamuna Sangama (Karaoke)',           artist: 'Anuraga Aralithu',               duration: '3:58', cover: '/bottle4.jpeg',               youtubeId: 'C_XbzG8qHCo', language: 'Kannada', era: '1980s' },
    { id: 213, title: 'Anupama Cheluvu (Karaoke)',                artist: 'Anupama',                        duration: '4:15', cover: '/bottle3.jpeg',               youtubeId: '9eObQw7Shv4', language: 'Kannada', era: '1980s' },
    { id: 214, title: 'Nammoora Mandara Hoove (Karaoke)',         artist: 'Aalemane',                       duration: '5:10', cover: '/gallery/promo-elegance.jpg', youtubeId: 'MUbYGWXgLWA', language: 'Kannada', era: '1980s' },
    { id: 215, title: 'Huttidare Kannada (Karaoke)',              artist: 'Akasmika',                       duration: '4:48', cover: '/bottle2.jpeg',               youtubeId: '8EQazuBu198', language: 'Kannada', era: '1980s' },
    { id: 216, title: 'Janumada Jodi (Karaoke)',                  artist: 'Janumada Jodi',                  duration: '4:22', cover: '/bottle3.jpeg',               youtubeId: 'cQhxNYVynuc', language: 'Kannada', era: '1990s' },
    { id: 217, title: 'Nooru Janmaku (Karaoke)',                  artist: 'America America',                duration: '4:05', cover: '/bottle4.jpeg',               youtubeId: 'CYKZ3wjUKhE', language: 'Kannada', era: '1990s' },
    { id: 218, title: 'Ninna Nodalentho (Karaoke)',               artist: 'Mussanje Maathu',                duration: '4:38', cover: '/gallery/promo-serenity.jpg', youtubeId: 'doc8BBsWLII', language: 'Kannada', era: '1990s' },
    { id: 219, title: 'Prema Chandrama (Karaoke)',                artist: 'Yajamana',                       duration: '4:30', cover: '/bottle2.jpeg',               youtubeId: 'JpDDD5UWVVQ', language: 'Kannada', era: '1990s' },

    // ── Janapada ──
    { id: 140, title: 'ಕೈ ಬಿಡಬ್ಯಾಡ ಕೈ ಬಿಡಬ್ಯಾಡ | Kai Bidabaad Kai Bidabaad', artist: 'Jhankar Music Folk Factory', duration: '6:38', cover: '/bottle2.jpeg', youtubeId: 'lAdKiIxHI1o', language: 'Kannada', genre: 'Janapada' },
    { id: 141, title: 'ಗಂಡಸರ ಪರಿಸ್ಥಿತಿ | Gandasara Paristhiti', artist: 'Lapang Raja', duration: '8:23', cover: '/bottle3.jpeg', youtubeId: 'CotNgQ3hs9A', language: 'Kannada', genre: 'Janapada' },
    { id: 142, title: 'ನನ್ನ ಮರ್ಜಿ | Nanna Marji', artist: 'Lapang Raja', duration: '5:47', cover: '/bottle4.jpeg', youtubeId: 'KGE9sHL425s', language: 'Kannada', genre: 'Janapada' },
    { id: 143, title: 'ಇಕಿ ನಮ್ಮ ಅಕ್ಕನ ಮಗಳ | Ikki Namma Akkan Magal', artist: 'Lapang Raja', duration: '5:00', cover: '/gallery/promo-serenity.jpg', youtubeId: 'TyQlZ_ACDck', language: 'Kannada', genre: 'Janapada' },
    { id: 144, title: 'ನಾ ಡ್ರೈವರ್ ನೀ ನನ್ನ ಲವರ್ | Naa Driver Ni Nann Lover', artist: 'Malu Nipanal Singer', duration: '8:17', cover: '/gallery/promo-elegance.jpg', youtubeId: 'kJcVqDTPSxc', language: 'Kannada', genre: 'Janapada' },
    { id: 145, title: 'ಕುಣೀತಾಳೋ ಕುಣೀತಾಳ ನೆಲಕ್ ಕಾಲ್ ಹತ್ತದಂಗ್ ಕುಣೀತಾಳೋ | Kunitalo Kunital Nelak Kal Hattadang Kunital', artist: 'Balu Belagundi Singer', duration: '6:59', cover: '/bottle2.jpeg', youtubeId: 'iOMqz4LbiMY', language: 'Kannada', genre: 'Janapada' },
    { id: 146, title: 'ಲಂಗಾ ದವನ್ಯಾಗ ಮಸ್ತ್ ಕಾಣತಿ ಲಾವಣ್ಯ | Langa Dawanyag Mast Kanati Lavanya', artist: 'Balu Belagundi Singer', duration: '5:10', cover: '/bottle3.jpeg', youtubeId: 'EKaQqmpRDtQ', language: 'Kannada', genre: 'Janapada' },
    { id: 147, title: 'ಏ ಮಾವಾ ನಿನ್ನ ಮಗಳ | A Mava Ninna Magala', artist: 'Malu Nipanal Singer', duration: '5:13', cover: '/bottle4.jpeg', youtubeId: '99bjndftjGg', language: 'Kannada', genre: 'Janapada' },
    { id: 148, title: 'ಹುಟ್ಟಿದ ಊರಿಗೆ ಹ್ವಾದರ ಕಟ್ಟಿ ಬಡಿತಾರ | Huttid Urigi Hodar Katti Baditar', artist: 'Balu Belagundi Singer', duration: '5:43', cover: '/gallery/promo-serenity.jpg', youtubeId: 'aIQpgca3EoM', language: 'Kannada', genre: 'Janapada' },
    { id: 149, title: 'ಮೈ ಲೈಪ್ ಮೈ ವೈಫ್ ನಿನಂತೂ ಆ ಟೈಪ್ | My Life My Wife', artist: 'Balu Belagundi Singer', duration: '5:18', cover: '/gallery/promo-elegance.jpg', youtubeId: 'uZJ4X3u2L8U', language: 'Kannada', genre: 'Janapada' },
    { id: 150, title: 'RANU BOMBAI KI RANU | Ranu Bombay Ki Ranu', artist: 'RATHOD TUNES', duration: '4:32', cover: '/bottle2.jpeg', youtubeId: '2voCBpYfFI4', language: 'Kannada', genre: 'Janapada' },
    { id: 151, title: 'ಏನ ಕುಣತ ನಿಂದ ಏನ ಕುಣತ | Yen Kunata Ninda Yen Kunata', artist: 'Balu Belagundi Singer', duration: '6:19', cover: '/bottle3.jpeg', youtubeId: 'J6GXrvLRZr4', language: 'Kannada', genre: 'Janapada' },
];

const karaokeTrackIds = new Set([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219]);

const trackMoodsById: Record<number, Mood[]> = {
    1: ['Party', 'Happy'],
    2: ['Happy', 'Driving'],
    3: ['Party', 'Happy'],
    4: ['Party', 'Driving'],
    5: ['Sad', 'Driving'],
    6: ['Happy', 'Driving'],
    7: ['Happy', 'Driving'],
    8: ['Happy', 'Driving'],
    9: ['Happy', 'Driving'],
    10: ['Sad', 'Driving'],
    11: ['Happy', 'Driving'],
    12: ['Happy', 'Driving'],
    13: ['Happy', 'Driving'],
    14: ['Sad', 'Driving'],
    15: ['Happy', 'Driving'],
    16: ['Party', 'Driving'],
    17: ['Happy', 'Driving'],
    18: ['Sad', 'Driving'],
    19: ['Party', 'Happy'],
    20: ['Party', 'Driving'],
    21: ['Happy', 'Party'],
    22: ['Party', 'Driving'],
    23: ['Happy', 'Driving'],
    24: ['Sad', 'Driving'],
    25: ['Sad', 'Driving'],
    26: ['Happy', 'Driving'],
    27: ['Happy', 'Driving'],
    28: ['Party', 'Happy'],
    29: ['Sad', 'Driving'],
    30: ['Party', 'Driving'],
    31: ['Sad', 'Driving'],
    32: ['Party', 'Happy'],
    33: ['Party', 'Happy'],
    34: ['Happy', 'Driving'],
    35: ['Sad', 'Driving'],
    36: ['Happy', 'Driving'],
    37: ['Happy', 'Driving'],
    38: ['Sad', 'Driving'],
    39: ['Sad', 'Driving'],
    40: ['Happy', 'Driving'],
    41: ['Party', 'Happy'],
    42: ['Happy', 'Driving'],
    43: ['Sad', 'Driving'],
    44: ['Sad', 'Driving'],
    45: ['Sad', 'Driving'],
    46: ['Party', 'Happy'],
    47: ['Happy', 'Driving'],
    48: ['Happy', 'Driving'],
    49: ['Party', 'Driving'],
    50: ['Party', 'Driving'],
    51: ['Happy', 'Driving'],
    52: ['Party', 'Happy'],
    53: ['Happy', 'Driving'],
    54: ['Sad', 'Driving'],
    55: ['Happy', 'Driving'],
    56: ['Sad', 'Driving'],
    57: ['Sad', 'Driving'],
    58: ['Party', 'Driving'],
    59: ['Party', 'Driving'],
    60: ['Happy', 'Driving'],
    61: ['Party', 'Driving'],
    62: ['Party', 'Happy'],
    63: ['Sad', 'Driving'],
    64: ['Party', 'Driving'],
    65: ['Driving', 'Happy'],
    66: ['Driving', 'Happy'],
    67: ['Party', 'Happy'],
    68: ['Party', 'Driving'],
    69: ['Party', 'Driving'],
    70: ['Happy', 'Party'],
    71: ['Sad', 'Driving'],
    72: ['Sad', 'Driving'],
    73: ['Happy', 'Driving'],
    74: ['Sad', 'Driving'],
    75: ['Sad', 'Driving'],
    76: ['Sad', 'Driving'],
    77: ['Happy', 'Driving'],
    78: ['Sad', 'Driving'],
    79: ['Sad', 'Driving'],
    80: ['Party', 'Driving'],
    81: ['Party', 'Happy'],
    82: ['Sad', 'Driving'],
    83: ['Party', 'Driving'],
    84: ['Sad', 'Driving'],
    85: ['Happy', 'Driving'],
    86: ['Sad', 'Driving'],
    87: ['Sad', 'Driving'],
    88: ['Happy', 'Driving'],
    89: ['Sad', 'Driving'],
    90: ['Sad', 'Driving'],
    91: ['Sad', 'Driving'],
    92: ['Happy', 'Driving'],
    93: ['Happy', 'Driving'],
    94: ['Driving', 'Happy'],
    95: ['Happy', 'Driving'],
    96: ['Happy', 'Driving'],
    97: ['Party', 'Driving'],
    98: ['Party', 'Happy'],
    99: ['Happy', 'Driving'],
    100: ['Happy', 'Driving'],
    101: ['Sad', 'Driving'],
    102: ['Happy', 'Driving'],
    103: ['Sad', 'Driving'],
    104: ['Sad', 'Driving'],
    105: ['Happy', 'Driving'],
    106: ['Sad', 'Driving'],
    107: ['Happy', 'Driving'],
    108: ['Happy', 'Driving'],
    109: ['Sad', 'Driving'],
    110: ['Happy', 'Driving'],
    111: ['Driving', 'Happy'],
    112: ['Sad', 'Driving'],
    113: ['Happy', 'Driving'],
    114: ['Party', 'Driving'],
    115: ['Sad', 'Driving'],
    116: ['Sad', 'Driving'],
    117: ['Happy', 'Driving'],
    118: ['Party', 'Driving'],
    119: ['Happy', 'Driving'],
    120: ['Party', 'Happy'],
    121: ['Sad', 'Driving'],
    122: ['Sad', 'Driving'],
    123: ['Sad', 'Driving'],
    124: ['Driving', 'Happy'],
    125: ['Sad', 'Driving'],
    126: ['Happy', 'Driving'],
    127: ['Party', 'Happy'],
    128: ['Sad', 'Driving'],
    129: ['Happy', 'Driving'],
    130: ['Driving', 'Happy'],
    131: ['Party', 'Driving'],
    132: ['Driving', 'Happy'],
    133: ['Sad', 'Driving'],
    134: ['Happy', 'Driving'],
    135: ['Happy', 'Driving'],
    136: ['Party', 'Driving'],
    137: ['Happy', 'Driving'],
    138: ['Party', 'Driving'],
    139: ['Sad', 'Driving'],
    140: ['Happy', 'Driving'],
    141: ['Sad', 'Driving'],
    142: ['Happy', 'Driving'],
    143: ['Happy', 'Driving'],
    144: ['Driving', 'Happy'],
    145: ['Party', 'Happy'],
    146: ['Happy', 'Driving'],
    147: ['Happy', 'Driving'],
    148: ['Sad', 'Driving'],
    149: ['Happy', 'Driving'],
    150: ['Party', 'Driving'],
    151: ['Happy', 'Driving'],
    200: ['Party', 'Happy'],
    201: ['Happy', 'Driving'],
    202: ['Party', 'Happy'],
    203: ['Sad', 'Driving'],
    204: ['Happy', 'Driving'],
    205: ['Party', 'Driving'],
    206: ['Happy', 'Driving'],
    207: ['Sad', 'Driving'],
    208: ['Happy', 'Party'],
    209: ['Party', 'Driving'],
    210: ['Happy', 'Driving'],
    211: ['Happy', 'Driving'],
    212: ['Happy', 'Driving'],
    213: ['Happy', 'Driving'],
    214: ['Happy', 'Driving'],
    215: ['Happy', 'Driving'],
    216: ['Happy', 'Driving'],
    217: ['Sad', 'Driving'],
    218: ['Sad', 'Driving'],
    219: ['Happy', 'Driving'],
};

export const tracks: Track[] = baseTracks.map((track) => ({
    ...track,
    moods: trackMoodsById[track.id] ?? ['Happy'],
    isKaraoke: karaokeTrackIds.has(track.id),
}));

export const mainTracks = tracks.filter((track) => !track.genre && !track.isKaraoke);

export const janapadaTracks = tracks.filter((track) => track.genre === 'Janapada');

export const karaokeTracks = tracks.filter((track) => track.isKaraoke && !track.genre);

export const getYouTubeTrackUrl = (track: Track) => `https://www.youtube.com/watch?v=${track.youtubeId}`;

export const getYouTubeErrorMessage = (code: number) => {
    switch (code) {
        case 2:
            return 'This song has an invalid YouTube link.';
        case 5:
            return 'This song could not be played in the browser.';
        case 100:
            return 'This song is no longer available on YouTube.';
        case 101:
        case 150:
            return 'This song cannot be embedded here. Open it on YouTube instead.';
        default:
            return 'This song could not be loaded from YouTube.';
    }
};
